# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ddbf04efc1835b3e60491eb94031275e98c8da402dad238ab1baec8dc3de51cccaeacffd7e798a78e5599e0456e1fa5f0afd61d357363eb1dce6cc4ec5ce53

test:
  secret_key_base: 99a794a72372fa5f304b26b4d36f456ae4812e4a2662ddab160b64fdf370af5a883f5bdb269b9129370fdaaa1848d95502db1fdb89ead739f91ce094dbfa8420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
